#include "il0373.h"

//
// Defines from Datasheet
//

// Delays pulled from STM32 code examples https://heltec.org/project/213-e-ink/
// as dataasheets does not specify them.
#define IL0373_RESET_LOW_MS 100
#define IL0373_RESET_HIGH_MS 100

#define IL0373_PANEL_SETTING 0x00
#define IL0373_PANER_SETTING_DISPLAY_RESOLUTION_BIT 6
#define IL0373_PANER_SETTING_DISPLAY_RESOLUTION_96x230 (0<<IL0373_PANER_SETTING_DISPLAY_RESOLUTION_BIT)  // POR
#define IL0373_PANER_SETTING_DISPLAY_RESOLUTION_96x252 (1<<IL0373_PANER_SETTING_DISPLAY_RESOLUTION_BIT)
#define IL0373_PANER_SETTING_DISPLAY_RESOLUTION_128x296 (2<<IL0373_PANER_SETTING_DISPLAY_RESOLUTION_BIT)
#define IL0373_PANER_SETTING_DISPLAY_RESOLUTION_160x296 (3<<IL0373_PANER_SETTING_DISPLAY_RESOLUTION_BIT)
#define IL0373_PANER_SETTING_LUT_BIT 5
#define IL0373_PANER_SETTING_LUT_FROM_OTP (0<<IL0373_PANER_SETTING_LUT_BIT)  // POR
#define IL0373_PANER_SETTING_LUT_FROM_REGISTER (1<<IL0373_PANER_SETTING_LUT_BIT)
#define IL0373_PANER_SETTING_BWR_BIT 4
#define IL0373_PANER_SETTING_BWR (0<<IL0373_PANER_SETTING_BWR_BIT)  // POR
#define IL0373_PANER_SETTING_BW (1<<IL0373_PANER_SETTING_BWR_BIT)
#define IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_BIT 3
#define IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_DOWN (0<<IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_BIT)
#define IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_UP (1<<IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_BIT)
#define IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_BIT 2
#define IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_LEFT (0<<IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_BIT)
#define IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_RIGHT (1<<IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_BIT)
#define IL0373_PANER_SETTING_BOOSTER_SWITCH_BIT 1
#define IL0373_PANER_SETTING_BOOSTER_SWITCH_OFF (0<<IL0373_PANER_SETTING_BOOSTER_SWITCH_BIT)
#define IL0373_PANER_SETTING_BOOSTER_SWITCH_ON (1<<IL0373_PANER_SETTING_BOOSTER_SWITCH_BIT)  // POR
#define IL0373_PANER_SETTING_SOFT_RESET_BIT 0
#define IL0373_PANER_SETTING_SOFT_RESET_ON (0<<IL0373_PANER_SETTING_SOFT_RESET_BIT)
#define IL0373_PANER_SETTING_SOFT_RESET_OFF (1<<IL0373_PANER_SETTING_SOFT_RESET_BIT)

#define IL0373_POWER_SETTING 0x01
#define IL0373_POWER_SETTING_SOURCE_POWER_BIT 1
#define IL0373_POWER_SETTING_SOURCE_POWER_EXTERNAL (0<<IL0373_POWER_SETTING_SOURCE_POWER_BIT)
#define IL0373_POWER_SETTING_SOURCE_POWER_INTERNAL_DC_DC (1<<IL0373_POWER_SETTING_SOURCE_POWER_BIT)
#define IL0373_POWER_SETTING_GATE_POWER_BIT 0
#define IL0373_POWER_SETTING_GATE_POWER_EXTERNAL (0<<IL0373_POWER_SETTING_GATE_POWER_BIT)
#define IL0373_POWER_SETTING_GATE_POWER_INTERNAL_DC_DC (1<<IL0373_POWER_SETTING_GATE_POWER_BIT)
#define IL0373_POWER_SETTING_VCOM_VOLTAGE_BIT 2
#define IL0373_POWER_SETTING_VCOM_VOLTAGE(value) (value<<IL0373_POWER_SETTING_VCOM_VOLTAGE_BIT)
#define IL0373_POWER_SETTING_VGH_VGL_VOLTAGE_BIT 0
#define IL0373_POWER_SETTING_VGH_VGL_VOLTAGE(value) (value<<IL0373_POWER_SETTING_VGH_VGL_VOLTAGE_BIT)
#define IL0373_POWER_SETTING_INTERNAL_VDH_FOR_BW(value) (value)
#define IL0373_POWER_SETTING_INTERNAL_VDL_FOR_BW(value) (value)
#define IL0373_POWER_SETTING_INTERNAL_VDHR_FOR_RED(value) (value)

#define IL0373_POWER_OFF 0x02

#define IL0373_POWER_OFF_SEQUENCE_SETTING 0x03
// d T_VDS_OF

#define IL0373_POWER_ON 0x04

#define IL0373_POWER_ON_MEASURE 0x05

#define IL0373_BOOSTER_SOFT_START 0x06
#define IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_BIT 6
#define IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_10MS (0<<IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_BIT) // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_20MS (1<<IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_30MS (2<<IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_40MS (3<<IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT 3
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_1 (0<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_2 (1<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_3 (2<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)  // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_4 (3<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_5 (4<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_6 (5<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_7 (6<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_8 (7<<IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT 0
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_0_27US (0<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_0_34US (1<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_0_40US (2<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_0_54US (3<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_0_80US (4<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_1_54US (5<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_3_34US (6<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_6_58US (7<<IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_BIT)  // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_BIT 6
#define IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_10MS (0<<IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_BIT) // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_20MS (1<<IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_30MS (2<<IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_40MS (3<<IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT 3
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_1 (0<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_2 (1<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_3 (2<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)  // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_4 (3<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_5 (4<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_6 (5<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_7 (6<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_8 (7<<IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT 0
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_0_27US (0<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_0_34US (1<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_0_40US (2<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_0_54US (3<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_0_80US (4<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_1_54US (5<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_3_34US (6<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_6_58US (7<<IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_BIT)  // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT 3
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_1 (0<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_2 (1<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_3 (2<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)  // POR
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_4 (3<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_5 (4<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_6 (5<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_7 (6<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_8 (7<<IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT 0
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_0_27US (0<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_0_34US (1<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_0_40US (2<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_0_54US (3<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_0_80US (4<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_1_54US (5<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_3_34US (6<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)
#define IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_6_58US (7<<IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_BIT)  // POR
//    5678 43 210
// 0b 0000 10 111


#define IL0373_DEEP_SLEEP 0x07
#define IL0373_DEEP_SLEEP_DATA 0xa5

#define IL0373_DATA_START_TRANSMISSION_1 0x10
// KPXL[1:8]
// ...
// KPXL[n-1:n]

#define IL0373_DATA_STOP 0x11
#define IL0373_DATA_STOP_DATA_FLAG_BIT 7 

#define IL0373_DISPLAY_REFRESH 0x12

#define IL0373_DATA_START_TRANSMISSION_2  0x13
// RPXL[1:8]
// ...
// RPXL[n-1:n]

#define IL0373_VOCM_LUT 0x20

#define IL0373_W2W_LUT 0x21

#define IL0373_B2W_LUT 0x22

#define IL0373_W2B_LUT 0x23

#define IL0373_B2B_LUT 0x24

#define IL0373_PLL_CONTROL 0x30
#define IL0373_PLL_CONTROL_M_BIT 3
#define IL0373_PLL_CONTROL_M(value) (value<<IL0373_PLL_CONTROL_M_BIT)
#define IL0373_PLL_CONTROL_N_BIT 0
#define IL0373_PLL_CONTROL_N(value) (value<<IL0373_PLL_CONTROL_N_BIT)

#define IL0373_TEMPERATURE_SENSOR_CALIBRATION 0x40
// LM[10:3]
// TSR[7:0]
// LM[2:0]

#define IL0373_TEMPERATURE_SENSOR_ENABLE 0x41
// TSE
// TO[3:0]

#define IL0373_TEMPERATURE_SENSOR_WRITE 0x42
// WATTR[7:0]
// WMSB[7:0]
// WLSB[7:0]

#define IL0373_TEMPERATURE_SENSOR_READ 0x43
// RMSB[7:0]
// RLSB[7:0]

#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING 0x50
#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING_BORDER_DATA_BIT 6
#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING_BORDER_DATA(value) (value<<IL0373_VCOM_AND_DATA_INTERVAL_SETTING_BORDER_DATA_BIT)
#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING_DATA_POLARITY_BIT 4
#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING_DATA_POLARITY(value) (value<<IL0373_VCOM_AND_DATA_INTERVAL_SETTING_DATA_POLARITY_BIT)
#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING_VCOM_AND_DATA_INTERVAL_BIT 0
#define IL0373_VCOM_AND_DATA_INTERVAL_SETTING_VCOM_AND_DATA_INTERVAL(value) (value<<IL0373_VCOM_AND_DATA_INTERVAL_SETTING_VCOM_AND_DATA_INTERVAL_BIT)


#define IL0373_LOW_POWER_DETECTION 0x51

#define IL0373_TCON_SETTING 0x60
// S2G[3:0]
// G2S[3:0]

#define IL0373_RESOLUTION_SETTING 0x61
#define IL0373_RESOLUTION_SETTING_VERTICAL_HIGH_BIT 0
#define IL0373_RESOLUTION_SETTING_VERTICAL_HIGH(value) (((value>>8)&0x01)<<IL0373_RESOLUTION_SETTING_VERTICAL_HIGH_BIT)
#define IL0373_RESOLUTION_SETTING_VERTICAL_LOW_BIT 0
#define IL0373_RESOLUTION_SETTING_VERTICAL_LOW(value) (value&0xFF)

#define IL0373_REVISION 0x70

#define IL0373_GET_STATUS 0x71
#define IL0373_GET_STATUS_PTL_FLAG_BIT 6
#define IL0373_GET_STATUS_I2C_ERR_BIT 5
#define IL0373_GET_STATUS_I2C_BUSYN_BIT 4
#define IL0373_GET_STATUS_DATA_FLAG_BIT 3
#define IL0373_GET_STATUS_PON_BIT 2
#define IL0373_GET_STATUS_POF_BIT 1
#define IL0373_GET_STATUS_BUSY_N_BIT 0

#define IL0373_AUTO_MEASURE_VCOM 0x80
#define IL0373_AUTO_MEASURE_VCOM_AMVT_BIT 4
#define IL0373_AUTO_MEASURE_VCOM_XON_BIT 3
#define IL0373_AUTO_MEASURE_VCOM_AMVS_BIT 2
#define IL0373_AUTO_MEASURE_VCOM_AMV_BIT 1
#define IL0373_AUTO_MEASURE_VCOM_AMVE_BIT 0

#define IL0373_VCOM_VALUE 0x81
// VV[5:0]

#define IL0373_VCM_DC_SETTING 0x82
#define IL0373_VCM_DC_SETTING_NEG_VOLTS(volts) ((uint8_t)((volts*100.0-10.0)/5.0))

#define IL0373_PARTIAL_WINDOW 0x90
// HRST[7:3
// HRED[7:3]
// VRST[8:0]
// VRED[8:0]
// PT_SCAN

#define IL0373_PARTIAL_IN 0x91

#define IL0373_PARTIAL_OUT 0x92

#define IL0373_PROGRAM_MODE 0xa0
#define IL0373_PROGRAM_MODE_DATA 0xa5

#define IL0373_ACTIVE_PROGRAM 0xa1

#define IL0373_READ_OTP 0xa2

#define IL0373_CASCADE_SETTING 0xe0
// Output clock enable/disable.
// 0: Output 0V at CL pin. (default)
// 1: Output clock at CL pin for slave chip. 
#define IL0373_CASCADE_SETTING_TSFIX_BIT 1
// Let the value of slave’s temperuature is same as the masters’.
// 0: Temperature value is defined by internal temperature sensor / external LM75. (default)
// 1: Temperature value is defined by TS_SET[7:0] registers. 
#define IL0373_CASCADE_SETTING_CCEN_BIT 0

#define IL0373_POWER_SAVING 0xe3
// VCOM power saving width (unit = line period)
#define IL0373_POWER_SAVING_VCOM_W_BIT 4
// Source power saving width (unit = 660nS)
#define IL0373_POWER_SAVING_SD_W_BIT 0

#define IL0373_FORCE_TEMPERATURE 0xe5
// TS_SET[7:0]

//
// Functions
//

// Helpers

void reset(eglib_t *eglib);

void reset(eglib_t *eglib) {
	hal_set_reset(eglib, 0);
	hal_delay_ms(eglib, IL0373_RESET_LOW_MS);
	hal_set_reset(eglib, 1);
	hal_delay_ms(eglib, IL0373_RESET_HIGH_MS);
}

void init_datasheet(eglib_t *eglib);

// HTEW0213Z16_V13 BWR 212x104
// https://resource.heltec.cn/download/e-ink/213/2.13b%26w%26r/HTEW0213Z16_V13/HTEW0213Z16_V13.pdf
// HTEW0213C38_V13 BWY 212x104
// https://resource.heltec.cn/download/e-ink/213/2.13b%26w%26y/HTEW0213C38_V13/HTEW0213C38_V13.pdf
// HTEW0213T5_V2 BW 212x104
// https://resource.heltec.cn/download/e-ink/213/2.13b%26w/HTEW0213T5_V2/HTEW0213T5_V2.pdf
	// HTEW0213I5F_V11 BW 212x104 (flexible screen)
	// https://resource.heltec.cn/download/e-ink/213/2.13b%26w-soft/HTEW0213I5F_V11%20/HTEW0213I5F_V11%20.pdf
void init_datasheet(eglib_t *eglib) {
	(void)eglib;
	// Reset the EPD driver IC
	// Booster soft start
	// Power setting*
	// Power on
	// Panel setting
	// PLL control*
	// Resolution setting

	// *BW only
}

void booster_soft_start(eglib_t *eglib);

void booster_soft_start(eglib_t *eglib) {
	hal_send_command_byte(eglib, IL0373_BOOSTER_SOFT_START);
	hal_send_data_byte(
		eglib,
		IL0373_BOOSTER_SOFT_START_PHASE_A_PERIOD_10MS |
		IL0373_BOOSTER_SOFT_START_PHASE_A_STRENGTH_3 |
		IL0373_BOOSTER_SOFT_START_PHASE_A_MIN_OFF_TIME_OF_GDR_6_58US
	);
	hal_send_data_byte(
		eglib,
		IL0373_BOOSTER_SOFT_START_PHASE_B_PERIOD_10MS |
		IL0373_BOOSTER_SOFT_START_PHASE_B_STRENGTH_3 |
		IL0373_BOOSTER_SOFT_START_PHASE_B_MIN_OFF_TIME_OF_GDR_6_58US
	);
	hal_send_data_byte(
		eglib,
		IL0373_BOOSTER_SOFT_START_PHASE_C_STRENGTH_3 |
		IL0373_BOOSTER_SOFT_START_PHASE_C_MIN_OFF_TIME_OF_GDR_6_58US
	);
}

void resolution_setting(eglib_t *eglib, uint8_t horizontal, uint16_t vertical);

void resolution_setting(eglib_t *eglib, uint8_t horizontal, uint16_t vertical) {
	hal_send_command_byte(eglib, IL0373_RESOLUTION_SETTING);
	hal_send_data_byte(eglib, horizontal);
	hal_send_data_byte(
		eglib,
		IL0373_RESOLUTION_SETTING_VERTICAL_HIGH(vertical)
	);
	hal_send_data_byte(
		eglib,
		IL0373_RESOLUTION_SETTING_VERTICAL_LOW(vertical)
	);
}

void init_bwr_and_bwy(eglib_t *eglib);

void init_bwr_and_bwy(eglib_t *eglib) {
	booster_soft_start(eglib);

	hal_send_command_byte(eglib, IL0373_POWER_ON);

	hal_send_command_byte(eglib, IL0373_PANEL_SETTING);
	hal_send_data_byte(
		eglib,
		IL0373_PANER_SETTING_DISPLAY_RESOLUTION_128x296 |
		IL0373_PANER_SETTING_LUT_FROM_OTP |
		IL0373_PANER_SETTING_BWR |
		IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_UP |
		IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_RIGHT |
		IL0373_PANER_SETTING_BOOSTER_SWITCH_ON |
		IL0373_PANER_SETTING_SOFT_RESET_ON
	);
	// FIXME Datasheet says IL0373_PANEL_SETTING accepts only one data byte,
	// but example code sends this...
	// hal_send_data_byte(eglib, 0x0d);

	hal_send_command_byte(eglib, IL0373_VCOM_AND_DATA_INTERVAL_SETTING);
	hal_send_data_byte(
		eglib,
		IL0373_VCOM_AND_DATA_INTERVAL_SETTING_BORDER_DATA(1) |
		IL0373_VCOM_AND_DATA_INTERVAL_SETTING_DATA_POLARITY(3) |
		IL0373_VCOM_AND_DATA_INTERVAL_SETTING_VCOM_AND_DATA_INTERVAL(7)
	);

	resolution_setting(eglib, 104, 212); // FIXME
}

void init_bw(eglib_t *eglib);

void init_bw(eglib_t *eglib) {
	hal_send_command_byte(eglib, IL0373_POWER_SETTING);
	hal_send_data_byte(
		eglib,
		IL0373_POWER_SETTING_SOURCE_POWER_INTERNAL_DC_DC |
		IL0373_POWER_SETTING_GATE_POWER_INTERNAL_DC_DC
	);
	hal_send_data_byte(
		eglib,
		IL0373_POWER_SETTING_VCOM_VOLTAGE(0) |
		IL0373_POWER_SETTING_VGH_VGL_VOLTAGE(0)
	);
	hal_send_data_byte(eglib, IL0373_POWER_SETTING_INTERNAL_VDH_FOR_BW(0x2b));
	hal_send_data_byte(eglib, IL0373_POWER_SETTING_INTERNAL_VDL_FOR_BW(0x2b));
	hal_send_data_byte(eglib, IL0373_POWER_SETTING_INTERNAL_VDHR_FOR_RED(0x03));

	booster_soft_start(eglib);

	hal_send_command_byte(eglib, IL0373_POWER_ON);
	hal_wait_not_busy(eglib);

	hal_send_command_byte(eglib, IL0373_PANEL_SETTING);
	hal_send_data_byte(
		eglib,
		IL0373_PANER_SETTING_DISPLAY_RESOLUTION_128x296 |
		IL0373_PANER_SETTING_LUT_FROM_REGISTER |
		IL0373_PANER_SETTING_BW |
		IL0373_PANER_SETTING_GATE_SCAN_DIRECTION_UP |
		IL0373_PANER_SETTING_SOURCE_SHIFT_DIRECTION_RIGHT |
		IL0373_PANER_SETTING_BOOSTER_SWITCH_ON |
		IL0373_PANER_SETTING_SOFT_RESET_OFF
	);
	// FIXME Datasheet says IL0373_PANEL_SETTING accepts only one data byte,
	// but example code sends this...
	// hal_send_data_byte(eglib, 0x0d);  //VCOM to 0V fast

	hal_send_command_byte(eglib, IL0373_PLL_CONTROL);
	hal_send_data_byte(
		eglib,
		IL0373_PLL_CONTROL_M(7) | IL0373_PLL_CONTROL_N(2)  // 50MHz
	);

	resolution_setting(eglib, 104, 212); // FIXME

	hal_send_command_byte(eglib, IL0373_VCM_DC_SETTING);
	hal_send_data_byte(eglib, IL0373_VCM_DC_SETTING_NEG_VOLTS(2.1));

	hal_send_command_byte(eglib, IL0373_VCOM_AND_DATA_INTERVAL_SETTING);
	hal_send_data_byte(
		eglib,
		IL0373_VCOM_AND_DATA_INTERVAL_SETTING_BORDER_DATA(2) |
		IL0373_VCOM_AND_DATA_INTERVAL_SETTING_DATA_POLARITY(1) |
		IL0373_VCOM_AND_DATA_INTERVAL_SETTING_VCOM_AND_DATA_INTERVAL(7)
	);
}

// display_t

static void init(eglib_t *eglib) {
	il0373_config_t *display_config;

	display_config = display_get_config(eglib);
	display_config->refreshing = false;

	reset(eglib);

	hal_comm_begin(eglib);

	init_bwr_and_bwy(eglib);
	// init_bw(eglib);

	hal_comm_end(eglib);


	coordinate_t u, v;
	coordinate_t display_width, display_height;
	display_get_dimension(eglib, &display_width, &display_height);
	hal_comm_begin(eglib);
	hal_send_command_byte(eglib, IL0373_DATA_START_TRANSMISSION_1);
	for(u=0;u<display_width;u++)
		for(v=0;v<display_height;v++)
			hal_send_data_byte(eglib, 0x00);
	hal_send_command_byte(eglib, IL0373_DATA_START_TRANSMISSION_2);
	for(u=0;u<display_width;u++)
		for(v=0;v<display_height;v++)
			hal_send_data_byte(eglib, 0xFF);
	hal_send_command_byte(eglib, IL0373_DATA_STOP);
	hal_comm_end(eglib);
};

static void sleep_in(eglib_t *eglib) {
	// TODO
	// Border floating
	// Enter into deep sleep mode
	(void)eglib;
};

static void sleep_out(eglib_t *eglib) {
	init(eglib);
};

static void get_dimension(
	eglib_t *eglib,
	coordinate_t *width, coordinate_t*height
) {
	il0373_config_t *display_config;

	display_config = display_get_config(eglib);

	*width = display_config->width;;
	*height = display_config->height;
};

static void get_color_depth(eglib_t *eglib, color_depth_t *color_depth) {
	(void)eglib;
	// FIXME bw or bwr
	*color_depth = EGLIB_COLOR_DEPTH_1BIT_PAGED;
}

static void draw_pixel_color(
	eglib_t *eglib,
	coordinate_t x, coordinate_t y, color_t color
) {
	(void)eglib;
	(void)x;
	(void)y;
	(void)color;
};

static void send_buffer(
	eglib_t *eglib,
	void *buffer_ptr,
	coordinate_t x, coordinate_t y,
	coordinate_t width, coordinate_t height
) {
	// uint8_t *buffer;
	coordinate_t display_width, display_height;

	// buffer = (uint8_t *)buffer_ptr;
	(void)buffer_ptr;
	(void)x;
	(void)y;
	(void)width;
	(void)height;

	display_get_dimension(eglib, &display_width, &display_height);

	hal_comm_begin(eglib);

	coordinate_t u, v;
	hal_send_command_byte(eglib, IL0373_DATA_START_TRANSMISSION_1);
	for(u=0;u<display_width;u++)
		for(v=0;v<display_height;v++)
			hal_send_data_byte(eglib, 0x00);
	hal_send_command_byte(eglib, IL0373_DATA_START_TRANSMISSION_2);
	for(u=0;u<display_width;u++)
		for(v=0;v<display_height;v++)
			hal_send_data_byte(eglib, 0x00);

	hal_comm_end(eglib);
}

static bool refresh(eglib_t *eglib) {
	il0373_config_t *display_config;

	display_config = display_get_config(eglib);

	if(display_config->refreshing){
		if(!hal_get_busy(eglib))
			return true;
		display_config->refreshing = false;
		return false;
	} else {
		hal_comm_begin(eglib);
		hal_send_command_byte(eglib, IL0373_DISPLAY_REFRESH);
		hal_comm_end(eglib);
		display_config->refreshing = true;
		return true;
	}
}

// Custom Functions

//
// display_t
//

const display_t il0373 = {
	.comm = {
		.four_wire_spi = &((hal_four_wire_spi_config_comm_t){
			.mode = 0,
			.bit_numbering = EGLIB_HAL_MSB_FIRST,
			.cs_setup_ns = 60,
			.cs_hold_ns = 20,
			// This says 40ns:
			// https://resource.heltec.cn/download/e-ink/213/2.13b%26w/HTEW0213T5_V2/IL0373.pdf
			// This says 100ns:
			// https://resource.heltec.cn/download/e-ink/213/2.13b%26w%26r/QYEG0213RWS800/QYEG0213RWS800F13_V1.2.pdf
			.cs_disable_ns = 100,
			.dc_setup_ns = 0,
			.dc_hold_ns = 0,
			// This says 70ns:
			// https://resource.heltec.cn/download/e-ink/213/2.13b%26w/HTEW0213T5_V2/IL0373.pdf
			// This says 50ns:
			// https://resource.heltec.cn/download/e-ink/213/2.13b%26w%26r/QYEG0213RWS800/QYEG0213RWS800F13_V1.2.pdf
			.sck_cycle_ns = 70,
		}),
		.three_wire_spi = NULL,
	},
	.init = init,
	.sleep_in = sleep_in,
	.sleep_out = sleep_out,
	.get_dimension = get_dimension,
	.get_color_depth = get_color_depth,
	.draw_pixel_color = draw_pixel_color,
	.send_buffer = send_buffer,
	.refresh = refresh,
};

//
// il0373_config_t
//

const il0373_config_t il0373_config_heltec_213_bwr = {

};