name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: git submodules
        run: |
          git submodule init
          git submodule update
      - name: Install autotools dependencies
        run: sudo apt-get -y install gnulib autoconf autoconf-archive automake
      - name: Install build dependencies
        run: sudo apt-get -y install gcc pkg-config libfreetype-dev libc-dev make check
      - name: Install test dependencies
        run: sudo apt-get -y install valgrind imagemagick
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install requirements.txt dependencies
        run: sudo apt-get -y install libclang-10-dev
      - name: Install Python dependencies
        run: pip install -rsphinx/requirements.txt
      - name: Install libopencm3_stm32f4 dependencies
        run: sudo apt-get install gcc-arm-none-eabi libnewlib-dev libnewlib-arm-none-eabi
      - name: autogen.sh
        run: ./autogen.sh
      - name: Linux build
        run: |
          mkdir build/
          cd build
          ../configure --with-libopencm3=../submodules/libopencm3/
          make
          make check-valgrind
          make update-html
          make dist
          cd ..
          rm -rf build
      - name: libopencm3_stm32f4 build
        run: |
          make -C submodules/libopencm3/ -j
          mkdir build/
          cd build
          ../configure --host=arm-none-eabi --enable-libopencm3_stm32f4 --with-libopencm3=../submodules/libopencm3/
          make
          make check
          cd ..
          rm -rf build
      - name: git status
        run: GIT_STATUS="$(git status --porcelain)" && [ -n "$GIT_STATUS" ] && { echo git status ; echo "$GIT_STATUS" ; echo git diff ; git diff ; exit 1 ; } || true