name: build
on: [push, pull_request]
env:
  COMMON_BUILD_DEPS: gcc pkg-config libfreetype-dev libc-dev make check
jobs:
  dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install autotools dependencies
        run: sudo apt-get -y install gnulib autoconf autoconf-archive automake
      - name: autogen.sh
        run: ./autogen.sh
      - name: Install build dependencies
        run: sudo apt-get -y install ${{env.COMMON_BUILD_DEPS}}
      - name: configure
        run: ./configure
      - name: make dist
        run: make dist
      - name: Rename
        run: mv eglib-$(cat .version).tar.gz eglib.tar.gz
      - name: Upload eglib.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: eglib.tar.gz
          path: eglib.tar.gz
  build_native:
    runs-on: ubuntu-20.04
    needs: dist
    steps:
      - uses: actions/checkout@v2
      - name: Submodules init & update
        run: |
          git submodule init
          git submodule update
      - name: Install build dependencies
        run: sudo apt-get -y install ${{env.COMMON_BUILD_DEPS}} valgrind imagemagick
      - name: Download eglib-$VERSION.tar.gz
        uses: actions/download-artifact@v2
      - name: Unpack
        run: tar zxf eglib.tar.gz
      - name: configure
        run: eglib-*/configure --with-libopencm3=submodules/libopencm3/
      - name: make
        run: make
      - name: make check-valgrind
        run: check-valgrind
      - name: make html
        run: make html
  build_libopencm3_stm32f4:
    runs-on: ubuntu-20.04
    needs: dist
    steps:
      - uses: actions/checkout@v2
      - name: Submodules init & update
        run: |
          git submodule init
          git submodule update
      - name: Install build dependencies
        run: sudo apt-get -y install ${{env.COMMON_BUILD_DEPS}} gcc-arm-none-eabi libnewlib-dev libnewlib-arm-none-eabi
      - name: Download eglib-$VERSION.tar.gz
        uses: actions/download-artifact@v2
      - name: Unpack
        run: tar zxf eglib.tar.gz
      - name: configure
        run: eglib-*/configure --host=arm-none-eabi --enable-libopencm3_stm32f4 --with-libopencm3=submodules/libopencm3/
      - name: make
        run: make