name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Submodules init & update
        run: |
          git submodule init
          git submodule update
      - name: Install build dependencies
        run: sudo apt-get -y install gnulib autoconf autoconf-archive automake valgrind gcc pkg-config imagemagick libfreetype-dev check libc-dev make
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure
      - name: make distcheck
        run: make distcheck
      - name: make all
        run: make all
      - name: make check-valgrind
        run: make check-valgrind
      - name: make distclean
        run: make distclean
      - name: git status
        run: GIT_STATUS="$(git status --porcelain)" && [ -n "$GIT_STATUS" ] && { echo git status ; echo "$GIT_STATUS" ; echo git diff ; git diff ; exit 1 ; } || true