name: build
on: [push, pull_request]
env:
  COMMON_BUILD_DEPS: gcc pkg-config libfreetype-dev libc-dev make
jobs:
  dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install autotools dependencies
        run: sudo apt-get -y install gnulib autoconf autoconf-archive automake
      - name: autogen.sh
        run: ./autogen.sh
      - name: Install build dependencies
        run: sudo apt-get -y install ${{env.COMMON_BUILD_DEPS}}
      - name: configure
        run: ./configure
      - name: make dist
        run: |
          make dist
          echo "VERSION=$(cat .version)" >> $GITHUB_ENV
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
  build_native:
    runs-on: ubuntu-20.04
    needs: dist
    steps:
      - uses: actions/checkout@v2
      - name: Submodules init & update
        run: |
          git submodule init
          git submodule update
      - name: Install build dependencies
        run: sudo apt-get -y install ${{env.COMMON_BUILD_DEPS}} valgrind imagemagick check
      - name: Download eglib-$VERSION.tar.gz
        uses: actions/download-artifact@v2
      - name: Unpack
        run: tar zxf eglib-${{env.VERSION}}.tar.gz
      - name: configure
        run: cd eglib-${{env.VERSION}} && ./configure --with-libopencm3=submodules/libopencm3/
      - name: make
        run: cd eglib-${{env.VERSION}} && make
      - name: make check-valgrind
        run: cd eglib-${{env.VERSION}} && check-valgrind
      - name: make html
        run: cd eglib-${{env.VERSION}} && make html
  build_libopencm3_stm32f4:
    runs-on: ubuntu-20.04
    needs: dist
    steps:
      - uses: actions/checkout@v2
      - name: Submodules init & update
        run: |
          git submodule init
          git submodule update
      - name: Install build dependencies
        run: sudo apt-get -y install ${{env.COMMON_BUILD_DEPS}} gcc-arm-none-eabi libnewlib-dev libnewlib-arm-none-eabi
      - name: Download eglib-$VERSION.tar.gz
        uses: actions/download-artifact@v2
      - name: Unpack
        run: tar zxf eglib-${{env.VERSION}}.tar.gz
      - name: configure
        run: cd eglib-${{env.VERSION}} && ./configure --host=arm-none-eabi --enable-libopencm3_stm32f4 --with-libopencm3=submodules/libopencm3/
      - name: make
        run: cd eglib-${{env.VERSION}} && make